name: Front End CI Pipeline

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install dependencies
        working-directory: Unify-front-end
        run: npm install

      - name: Run tests
        # ignore test for now as it is not implemented yet
        working-directory: Unify-front-end
        run: echo "Skipping tests"


      - name: Build app
        working-directory: Unify-front-end
        run: eas build --platform all

      - name: Deploy updates
        working-directory: Unify-front-end
        run: eas update